#ifndef CACONSTANTS
#define CACONSTANTS

#define DEVICE_OK                      0
#define DEVICE_ERR                     1 // generic, undefined error
#define DEVICE_INVALID_PROPERTY        2
#define DEVICE_INVALID_PROPERTY_VALUE  3
#define DEVICE_DUPLICATE_PROPERTY      4
#define DEVICE_INVALID_PROPERTY_TYPE   5
#define DEVICE_NATIVE_MODULE_FAILED    6 // unable to load or initialize native module
#define DEVICE_UNSUPPORTED_DATA_FORMAT 7 // we don't know how to handle camera data
#define DEVICE_INTERNAL_INCONSISTENCY  8 // internal data structures are corrupted
#define DEVICE_NOT_SUPPORTED           9
#define DEVICE_UNKNOWN_LABEL           10
#define DEVICE_UNSUPPORTED_COMMAND     11
#define DEVICE_UNKNOWN_POSITION        12
#define DEVICE_NO_CALLBACK_REGISTERED  13
#define DEVICE_SERIAL_COMMAND_FAILED   14
#define DEVICE_SERIAL_BUFFER_OVERRUN   15
#define DEVICE_SERIAL_INVALID_RESPONSE 16
#define DEVICE_SERIAL_TIMEOUT          17
#define DEVICE_SELF_REFERENCE          18
#define DEVICE_NO_PROPERTY_DATA        19
#define DEVICE_DUPLICATE_LABEL         20
#define DEVICE_INVALID_INPUT_PARAM     21
#define DEVICE_BUFFER_OVERFLOW         22
#define DEVICE_NONEXISTENT_CHANNEL     23
#define DEVICE_INVALID_PROPERTY_LIMTS  24
#define DEVICE_SNAP_IMAGE_FAILED       25
#define DEVICE_IMAGE_PARAMS_FAILED     26
#define DEVICE_CORE_FOCUS_STAGE_UNDEF  27
#define DEVICE_CORE_EXPOSURE_FAILED    28
#define DEVICE_CORE_CONFIG_FAILED      29
#define DEVICE_CAMERA_BUSY_ACQUIRING   30
#define DEVICE_INCOMPATIBLE_IMAGE      31
#define DEVICE_CAN_NOT_SET_PROPERTY    32
#define DEVICE_CORE_CHANNEL_PRESETS_FAILED  33
#define DEVICE_LOCALLY_DEFINED_ERROR   34
#define DEVICE_NOT_CONNECTED           35

#endif // CACONSTANTS

